//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmy
    {
        public int IdFirmy { get; set; }
        public int IdSiedzibyFirmy { get; set; }
        public string NazwaFirmy { get; set; }
        public string Nip { get; set; }
        public string Regon { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string NrBudynku { get; set; }
        public string NrLokalu { get; set; }
        public string KodPocztowy { get; set; }
        public string Poczta { get; set; }
        public string NrTelefonu { get; set; }
        public string Kraj { get; set; }
        public string Email { get; set; }
        public string StronaWWW { get; set; }
        public string NrKonta { get; set; }
    }
}
